/**
 * @(#)AbstractCustSysMenu.java
 *
 * Copyright (c) 2016 HiTRUST Incorporated. All rights reserved.
 *
 * Description : CustSysMenu base model
 * 
 * Modify History:
 *  v1.00, 2016/06/06, Yann
 *   1) First release, 二階
 *  
 */
package com.hitrust.bank.model.base;

import java.io.Serializable;

import com.hitrust.bank.model.AclCommand;

/**
 * CustSysMenu generated by hbm2java
 */
public class AbstractCustSysMenu extends AclCommand implements Serializable {

	private static final long serialVersionUID = 4930346546432780381L;
	
	// =============== KEY ===============
	private AbstractCustSysMenu.Id id; // 複合 KEY
	
	// =============== Table Attribute ===============
	private String menuName;
	private Integer serl;

	// =============== Getter & Setter ===============
	public AbstractCustSysMenu.Id getId() {
		return this.id;
	}
	
	public void setId(AbstractCustSysMenu.Id id) {
		this.id = id;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getSerl() {
		return this.serl;
	}

	public void setSerl(Integer serl) {
		this.serl = serl;
	}

	// =============== 複合 KEY ===============
	public static class Id implements Serializable {
		private static final long serialVersionUID = 6246203002689587864L;
		
		// =============== Table Attribute ===============
		private String lngn;
		private String menuId;
		
		// =============== Getter & Setter ===============
		public String getLngn() {
			return this.lngn;
		}
		public void setLngn(String lngn) {
			this.lngn = lngn;
		}
		public String getMenuId() {
			return this.menuId;
		}
		public void setMenuId(String menuId) {
			this.menuId = menuId;
		}
	}
}
