/**
 * @(#)AbstractCustOptLog.java
 *
 * Copyright (c) 2016 HiTRUST Incorporated. All rights reserved.
 *
 * Description : CustOptLog base model
 * 
 * Modify History:
 *  v1.00, 2016/06/06, Yann
 *   1) First release, 二階
 *  
 */
package com.hitrust.bank.model.base;

import java.io.Serializable;
import java.util.Date;

import com.hitrust.bank.model.AclCommand;

/**
 * CustOptLog generated by hbm2java
 */
public class AbstractCustOptLog extends AclCommand implements Serializable {
	
	private static final long serialVersionUID = -4802885767602910745L;
	
	// =============== Table Attribute ===============
	private String logNo;
	private String userId;
	private String userName;
	private String fnctId;
	private Date oprtDttm;
	private String action;
	private String rslt;
	private String ipAddr;
	private String beforeId;
	private String afterId;
	private String custSerl;

	// =============== Getter & Setter ===============
	public String getLogNo() {
		return this.logNo;
	}

	public void setLogNo(String logNo) {
		this.logNo = logNo;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFnctId() {
		return this.fnctId;
	}

	public void setFnctId(String fnctId) {
		this.fnctId = fnctId;
	}

	public Date getOprtDttm() {
		return this.oprtDttm;
	}

	public void setOprtDttm(Date oprtDttm) {
		this.oprtDttm = oprtDttm;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getRslt() {
		return this.rslt;
	}

	public void setRslt(String rslt) {
		this.rslt = rslt;
	}

	public String getIpAddr() {
		return this.ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	public String getBeforeId() {
		return this.beforeId;
	}

	public void setBeforeId(String beforeId) {
		this.beforeId = beforeId;
	}

	public String getAfterId() {
		return this.afterId;
	}

	public void setAfterId(String afterId) {
		this.afterId = afterId;
	}

	public String getCustSerl() {
		return this.custSerl;
	}

	public void setCustSerl(String custSerl) {
		this.custSerl = custSerl;
	}

}
