/**
 * @(#)AbstractNewsMsg.java
 *
 * Copyright (c) 2016 HiTRUST Incorporated. All rights reserved.
 *
 * Description : NewsMsg base model
 * 
 * Modify History:
 *  v1.00, 2016/06/06, Yann
 *   1) First release, 二階
 *  
 */
package com.hitrust.bank.model.base;

import java.io.Serializable;
import java.util.Date;

import com.hitrust.bank.model.AclCommand;

/**
 * NewsMsg generated by hbm2java
 */
public class AbstractNewsMsg extends AclCommand implements Serializable {
	
	private static final long serialVersionUID = 4286258173683451080L;
	
	// =============== Table Attribute ===============
	private String seq;
	private String type;
	private String title;
	private String content;
	private Date bgnDate;
	private Date endDate;
	private Integer serl;
	private String cretUser;
	private Date cretDttm;
	private String mdfyUser;
	private Date mdfyDttm;

	// =============== Getter & Setter ===============
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getBgnDate() {
		return this.bgnDate;
	}

	public void setBgnDate(Date bgnDate) {
		this.bgnDate = bgnDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getSerl() {
		return this.serl;
	}

	public void setSerl(Integer serl) {
		this.serl = serl;
	}

	public String getCretUser() {
		return this.cretUser;
	}

	public void setCretUser(String cretUser) {
		this.cretUser = cretUser;
	}

	public Date getCretDttm() {
		return this.cretDttm;
	}

	public void setCretDttm(Date cretDttm) {
		this.cretDttm = cretDttm;
	}

	public String getMdfyUser() {
		return this.mdfyUser;
	}

	public void setMdfyUser(String mdfyUser) {
		this.mdfyUser = mdfyUser;
	}

	public Date getMdfyDttm() {
		return this.mdfyDttm;
	}

	public void setMdfyDttm(Date mdfyDttm) {
		this.mdfyDttm = mdfyDttm;
	}

}
