/**
 * @(#)AbstractCustSysFnct.java
 *
 * Copyright (c) 2016 HiTRUST Incorporated. All rights reserved.
 *
 * Description : CustSysFnct base model
 * 
 * Modify History:
 *  v1.00, 2016/06/06, Yann
 *   1) First release, 二階
 *  
 */
package com.hitrust.bank.model.base;

import java.io.Serializable;

import com.hitrust.bank.model.AclCommand;

/**
 * CustSysFnct generated by hbm2java
 */
public class AbstractCustSysFnct extends AclCommand implements Serializable {
	
	private static final long serialVersionUID = 6369624080008896606L;
	
	// =============== KEY ===============
	private AbstractCustSysFnct.Id id; // 複合 KEY
	
	// =============== Table Attribute ===============
	private String menuId;
	private String fnctName;
	private String isUse;
	private String isSet;
	private String url;
	private Integer serl;

	// =============== Getter & Setter ===============
	public AbstractCustSysFnct.Id getId() {
		return this.id;
	}
	
	public void setId(AbstractCustSysFnct.Id id) {
		this.id = id;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getFnctName() {
		return this.fnctName;
	}

	public void setFnctName(String fnctName) {
		this.fnctName = fnctName;
	}

	public String getIsUse() {
		return this.isUse;
	}

	public void setIsUse(String isUse) {
		this.isUse = isUse;
	}

	public String getIsSet() {
		return this.isSet;
	}

	public void setIsSet(String isSet) {
		this.isSet = isSet;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getSerl() {
		return this.serl;
	}

	public void setSerl(Integer serl) {
		this.serl = serl;
	}

	// =============== 複合 KEY ===============
	public static class Id implements Serializable {
		private static final long serialVersionUID = 4891083234192017053L;
		
		// =============== Table Attribute ===============
		private String lngn;
		private String fnctId;
		
		// =============== Getter & Setter ===============
		public String getLngn() {
			return this.lngn;
		}
		public void setLngn(String lngn) {
			this.lngn = lngn;
		}
		public String getFnctId() {
			return this.fnctId;
		}
		public void setFnctId(String fnctId) {
			this.fnctId = fnctId;
		}
	}
}
